### ISSUE TITLE
Insertion of cradle can break the wheel axel

### ISSUE THREAD

**Issue by mwelling** [biomurph/Mouse#1]
Should add a caution when inserting the cradle as it can break the wheel from the axel if not inserted carefully.

Sad to get that far just to snap the axel off into the encoder.

**Comment by biomurph** [comment]
Oh No!
I will add that note to the instructions.
Please contact me biomurph at gmail to work out a replacement for that.

**Comment by biomurph** [comment]
@mwelling I have extra wheel cradles and can ship you of you can't print your own

**Comment by mwelling** [comment]
I am okay, somehow I ended up with two mice. Thanks for the offer though.

**Comment by biomurph** [comment]
Two mice! You lucky bugger!
