### ISSUE TITLE
HID select switch (SW4) footprint

### ISSUE THREAD

**Issue by vektorious** [biomurph/Mouse#3]
I am trying to source all the parts on DigiKey and apparently the HID select switch (SW4) is the only thing which I can't find and I where I am not sure about an equivalent replacement. 

It's supposed to be the slider switch [SSSS810701 from Alps](https://www.alps.com/prod/info/E/HTML/Switch/Slide/SSSS8/SSSS810701.html) and I was looking at the footprint of the kicad_pcb file to get a similar ON-ON switch but I got a bit confused (probably a case of newbie confusion). The footprint has seven pads but as far as I can see the Alps switch has only 3 pins. Is the footprint actually universal for 3 and 4 pin switches Unfortunately I can't open the kicad.pro file because something with the libraries goes wrong but the connections in the .kicad_pcb file suggest that. That's why I chose [this 4 pin switch](https://www.digikey.de/product-detail/de/PCM12SMTR/401-2016-1-ND/1640125/?itemSeq=275199190) as a replacement. 

I am sorry if this is totally obvious but are my assumptions correct? 

Thank you in advance! 
Alex

**Comment by biomurph** [comment]
@vektorious Thanks for bringing the issue up.
The slider switch can be found on Mouser
https://www.mouser.com/ProductDetail/ALPS/SSSS810701?qs=%2fha2pyFaduiE%252bdzMwfk4uUaPOkxM%252bYluMos14K6bstY%3d
if that link doesn't work, please try to do a search for the part SSSS810701.
You can also check Octopart for other suppliers.

Regarding the kicad files not working, that is another issue... I see the problem, and I will get it fixed asap.

**Comment by biomurph** [comment]
@vektorious I repaired the parts library paths. Please check to see if that works for you.

**Comment by vektorious** [comment]
@biomurph thank you!

The library seems to work but I get this warning:

> Alias 'ADS1291/2' not found in library:
'/Users/xxxx/GitHub/Mouse/Hardware/KiCad/Mouse/Parts_Library/Solutions.dcm'
at line 3 offset 15

And KiCad is telling me that I'm missing some libraries but I can open all the files and everything is displayed correctly now (might be a problem with my KiCad installation).

I was looking for an alternative at DigiKey because shipping gets quite expensive for ordering just a few parts and in total there are less parts available at mouser. But now I'm quite confident that the switch I chose at DigiKey should fit!

**Comment by biomurph** [comment]
That warning is OK to ignore. The schematic doesn't use the ADS1291/2 so you're g to g.
Glad that the digikey part fits! If you add the part number as an alternative to the BOM, and then send a pull request, we can track your contribution to the Mouse!

**Comment by vektorious** [comment]
Just a quick update. I finally got all the parts from digikey and [the switch I got](https://www.digikey.de/product-detail/de/PCM12SMTR/401-2016-1-ND/1640125/?itemSeq=275199190) perfectly fits the footprint. I will add the part number (401-2016-1-ND)  to the BOM when I was able to fully rebuild the mouse an it actually works!
