### ISSUE TITLE
Flash bootloader

### ISSUE THREAD

**Issue by vektorious** [biomurph/Mouse#4]
I'm rebuilding the mouse basically from scratch and was wondering how I can flash the bootloader on the Arduino myself (I'm still learning). I found this [this guide](https://electronut.in/bootloader-atmega32u4/) and wanted to be sure if I can follow it and use the microUSB connection to get the bootloader on the chip. 

Thanks in advance!

**Comment by biomurph** [comment]
@vektorious you will need to install the bootloader before you can use the USB port to communicate with the ATmega32u4. For that, you will have to connect to the ICSP (In Circuit Serial Programming) pads. Those are the six SMT pads on the top of the board just above the PPH prototyping area.
Double check the schematic and PCB layout to make sure you get the connections right. Here's a tutorial on how to upload the bootloader
https://learn.sparkfun.com/tutorials/installing-an-arduino-bootloader/all
When I did this, I use the Arduino IDE to flash the 'Arduino Leonardo' bootloader to the mouse. Once that's done, you can program the mouse just like a Leonardo.
