### ISSUE TITLE
Patents, other Questions

### ISSUE THREAD

**Issue by tderflinger** [biomurph/Mouse#5]
Hi!
First of all, thanks for this great super mouse! I have a few questions:
- Is this design patent free?
- Can I buy an assembled mouse from you, or do I need to find an assembly company to do that for me?
- Do you have designs for the shell?

Thanks again for this cool idea!

**Comment by biomurph** [comment]
@tderflinger 
Hey, thanks for your interest in my Open Source Mouse! Here are your answers.

* There is not a patent on this design. It is Open Source. Please see the [OSHWA](www.oshwa.org) website for how to make sure that you are playing well with others. Basically, if you make anything from it, or make it and publish anything, you must attribute to me the work.

* This project was a gift in the shwag bag for the 2018 Open Source Hardware Summit. There are no more populated boards left. Also, the Mouse Eye Sensors and lenses are not available. I have some in my lab that I could sell you at cost plus a tiny amount. If you're interested, please let me know. All the other parts are available.

* I don't have any designs for the shell. That's on you.

You're welcome! I'm happy to sell you the EOL parts (Sensor and Lens) at a very good rate. LMK if you're interested. All the other parts are easy to solder by hand of with a stencil, paste, and reflow-gun.

**Comment by tderflinger** [comment]
Hi BioMurph!

Thanks for offering to sell the EOL parts. When there is a need I will gladly come back to you.

I am relatively new to hardware and would like to give the design to a third party company to produce one piece for me.
Already, I have installed KiCad and looked at the PCB. Somehow I could not find the BOM with all the parts needed. Do you have a file with the parts numbers need to produce the mouse?

Regards,
-Tommy

**Comment by biomurph** [comment]
The build is not too hard, but I understand that without experience it can be daunting.
I use [BetaLayout](https://us.beta-layout.com/pcb/) for prototypes. They give a free stencil, which makes assembly easy. Maybe there is a hacker space in your area that can assist?

The BOM is in the repo, in the `plots` file.

**Comment by tderflinger** [comment]
All right, thanks for this information! I will check out BetaLayout.
