### ISSUE TITLE
typo in image

### ISSUE THREAD

**Issue by millette** [biomurph/Mouse#6]
Text (and repo) mentions ADNS2026 but the image https://github.com/biomurph/Mouse/blob/master/images/mouseAnatomy.png says "ADNS2016".

**Comment by fireattack** [comment]
And the SparkFun link is a breakout for "ADNS2620".

**Comment by biomurph** [comment]
Thanks! Nice to see some interest in the Mouse project!
Did you folks get one at the Summit a couple years ago?
Just getting to it in the COVID time of digging through old schwag bags?

**Comment by fireattack** [comment]
> Thanks! Nice to see some interest in the Mouse project!
> Did you folks get one at the Summit a couple years ago?
> Just getting to it in the COVID time of digging through old schwag bags?

Someone posted it to Hacker News: https://news.ycombinator.com/item?id=23041747

You probably want to drop some insights there too!
